openapi: 3.0.0
info:
  title: CCS Vehicle Tracking API Gateway
  version: 1.0.0
  description: Central API Gateway for CCS Vehicle Tracking System
  contact:
    name: CCS Team
    email: support@ccs.com

servers:
  - url: https://localhost:7000
    description: Development server

paths:
  /vehicles/telemetry:
    post:
      tags:
        - Vehicles
      summary: Send vehicle telemetry data
      description: Receives telemetry information from vehicles including location, speed, and status
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/VehicleTelemetry'
      responses:
        '202':
          description: Telemetry accepted and processed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TelemetryResponse'
        '400':
          description: Bad request
        '500':
          description: Internal server error

  /vehicles/emergency:
    post:
      tags:
        - Vehicles
      summary: Send emergency signal
      description: Receives emergency signals from vehicles (panic button, accidents, mechanical issues)
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EmergencySignal'
      responses:
        '202':
          description: Emergency signal accepted and processed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EmergencyResponse'
        '400':
          description: Bad request
        '500':
          description: Internal server error

  /vehicles/emergencies:
    get:
      tags:
        - Vehicles
      summary: Get recent emergencies
      description: Retrieves a list of recent emergency signals
      responses:
        '200':
          description: List of emergencies retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EmergenciesList'
        '500':
          description: Internal server error

  /health:
    get:
      tags:
        - Health
      summary: Health check
      description: Returns the health status of the API Gateway
      responses:
        '200':
          description: Gateway is healthy
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HealthStatus'

  /health/ingestion:
    get:
      tags:
        - Health
      summary: Check ingestion service health
      description: Returns the health status of the ingestion service
      responses:
        '200':
          description: Ingestion service is healthy
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HealthStatus'

components:
  schemas:
    VehicleTelemetry:
      type: object
      required:
        - vehicleId
        - vehicleType
        - latitude
        - longitude
        - speed
      properties:
        vehicleId:
          type: string
          example: "TRUCK001"
        vehicleType:
          type: integer
          enum: [1, 2, 3, 4, 5]
          example: 1
        latitude:
          type: number
          format: double
          example: 4.710989
        longitude:
          type: number
          format: double
          example: -74.072092
        speed:
          type: number
          format: double
          example: 65.5
        direction:
          type: number
          format: double
          example: 45.0
        isMoving:
          type: boolean
          example: true
        engineOn:
          type: boolean
          example: true
        fuelLevel:
          type: number
          format: double
          example: 75.0
        cargoTemperature:
          type: number
          format: double
          example: 18.5
        cargoStatus:
          type: string
          example: "Normal"
        isPlannedStop:
          type: boolean
          example: false
        timestamp:
          type: string
          format: date-time
          example: "2024-01-15T10:30:00Z"

    EmergencySignal:
      type: object
      required:
        - vehicleId
        - emergencyType
        - latitude
        - longitude
        - description
      properties:
        vehicleId:
          type: string
          example: "TRUCK001"
        emergencyType:
          type: integer
          enum: [1, 2, 3, 4]
          example: 1
        source:
          type: string
          example: "panic_button"
        latitude:
          type: number
          format: double
          example: 4.710989
        longitude:
          type: number
          format: double
          example: -74.072092
        description:
          type: string
          example: "Driver pressed panic button - possible robbery"
        additionalData:
          type: string
          example: "{\"driverId\": \"DRV123\", \"lastSpeed\": 0.0}"

    TelemetryResponse:
      type: object
      properties:
        message:
          type: string
          example: "Telemetry received"
        telemetryId:
          type: string
          format: uuid
          example: "1462e414-3eeb-419f-8885-5e780751095e"

    EmergencyResponse:
      type: object
      properties:
        message:
          type: string
          example: "Emergency signal received and processed"
        emergencyId:
          type: string
          format: uuid
          example: "010bab13-b3fe-4192-98d2-e60fd8615133"
        priority:
          type: string
          example: "HIGH"
        timestamp:
          type: string
          format: date-time

    EmergenciesList:
      type: object
      properties:
        count:
          type: integer
          example: 5
        emergencies:
          type: array
          items:
            $ref: '#/components/schemas/EmergencyItem'

    EmergencyItem:
      type: object
      properties:
        emergencyId:
          type: string
        vehicleId:
          type: string
        emergencyType:
          type: integer
        source:
          type: string
        description:
          type: string
        createdAt:
          type: string
          format: date-time
        isResolved:
          type: boolean

    HealthStatus:
      type: object
      properties:
        status:
          type: string
          example: "Healthy"
        timestamp:
          type: string
          format: date-time
        service:
          type: string
        version:
          type: string